drop table  if exists animal;
create table animal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	nombreComun TEXT,
	nombreCientifico TEXT
);
insert into animal (nombreComun, nombreCientifico) values ('Dark-winged trumpeter', 'Psophia viridis');
insert into animal (nombreComun, nombreCientifico) values ('Golden-mantled ground squirrel', 'Spermophilus lateralis');
insert into animal (nombreComun, nombreCientifico) values ('Javan gold-spotted mongoose', 'Herpestes javanicus');
insert into animal (nombreComun, nombreCientifico) values ('Giant anteater', 'Myrmecophaga tridactyla');
insert into animal (nombreComun, nombreCientifico) values ('Emerald green tree boa', 'Boa caninus');
insert into animal (nombreComun, nombreCientifico) values ('Cat, cape wild', 'Felis libyca');
insert into animal (nombreComun, nombreCientifico) values ('Falcon, prairie', 'Falco mexicanus');
insert into animal (nombreComun, nombreCientifico) values ('Golden jackal', 'Canis aureus');
insert into animal (nombreComun, nombreCientifico) values ('Bustard, stanley', 'Neotis denhami');
insert into animal (nombreComun, nombreCientifico) values ('Fisher', 'Martes pennanti');
insert into animal (nombreComun, nombreCientifico) values ('Fox, asian red', 'Vulpes vulpes');
insert into animal (nombreComun, nombreCientifico) values ('Red phalarope', 'Phalaropus fulicarius');
insert into animal (nombreComun, nombreCientifico) values ('Malleefowl', 'Leipoa ocellata');
insert into animal (nombreComun, nombreCientifico) values ('Mongoose, eastern dwarf', 'Helogale undulata');
insert into animal (nombreComun, nombreCientifico) values ('Beisa oryx', 'Oryx gazella');
insert into animal (nombreComun, nombreCientifico) values ('Tropical buckeye butterfly', 'Junonia genoveua');
insert into animal (nombreComun, nombreCientifico) values ('Four-spotted skimmer', 'Libellula quadrimaculata');
insert into animal (nombreComun, nombreCientifico) values ('Bandicoot, southern brown', 'Isoodon obesulus');
insert into animal (nombreComun, nombreCientifico) values ('Common palm civet', 'Paradoxurus hermaphroditus');
insert into animal (nombreComun, nombreCientifico) values ('Otter, oriental short-clawed', 'Aonyx cinerea');
insert into animal (nombreComun, nombreCientifico) values ('Saddle-billed stork', 'Ephipplorhynchus senegalensis');
insert into animal (nombreComun, nombreCientifico) values ('Magpie, australian', 'Gymnorhina tibicen');
insert into animal (nombreComun, nombreCientifico) values ('Grey fox', 'Vulpes cinereoargenteus');
insert into animal (nombreComun, nombreCientifico) values ('Large cormorant', 'Phalacrocorax carbo');
insert into animal (nombreComun, nombreCientifico) values ('Nyala', 'Tragelaphus angasi');
insert into animal (nombreComun, nombreCientifico) values ('Green-winged trumpeter', 'Psophia viridis');
insert into animal (nombreComun, nombreCientifico) values ('Waved albatross', 'Diomedea irrorata');
insert into animal (nombreComun, nombreCientifico) values ('Violet-crested turaco', 'Tauraco porphyrelophus');
insert into animal (nombreComun, nombreCientifico) values ('Black-cheeked waxbill', 'Estrilda erythronotos');
insert into animal (nombreComun, nombreCientifico) values ('Northern phalarope', 'Phalaropus lobatus');
insert into animal (nombreComun, nombreCientifico) values ('Rattlesnake, dusky', 'Crotalus triseriatus');
insert into animal (nombreComun, nombreCientifico) values ('Common long-nosed armadillo', 'Dasypus novemcinctus');
insert into animal (nombreComun, nombreCientifico) values ('Brolga crane', 'Grus rubicundus');
insert into animal (nombreComun, nombreCientifico) values ('Woodchuck', 'Marmota monax');
insert into animal (nombreComun, nombreCientifico) values ('Common wombat', 'Vombatus ursinus');
insert into animal (nombreComun, nombreCientifico) values ('Cat, civet', 'Bassariscus astutus');
insert into animal (nombreComun, nombreCientifico) values ('Kongoni', 'Alcelaphus buselaphus cokii');
insert into animal (nombreComun, nombreCientifico) values ('Blue-tongued skink', 'Tiliqua scincoides');
insert into animal (nombreComun, nombreCientifico) values ('African snake (unidentified)', 'unavailable');
insert into animal (nombreComun, nombreCientifico) values ('Indian star tortoise', 'Geochelone elegans');
insert into animal (nombreComun, nombreCientifico) values ('White-faced whistling duck', 'Dendrocygna viduata');
insert into animal (nombreComun, nombreCientifico) values ('Grey mouse lemur', 'Microcebus murinus');
insert into animal (nombreComun, nombreCientifico) values ('Sable antelope', 'Hippotragus niger');
insert into animal (nombreComun, nombreCientifico) values ('Cereopsis goose', 'Cereopsis novaehollandiae');
insert into animal (nombreComun, nombreCientifico) values ('Red-necked wallaby', 'Macropus rufogriseus');
insert into animal (nombreComun, nombreCientifico) values ('Sage hen', 'Centrocercus urophasianus');
insert into animal (nombreComun, nombreCientifico) values ('Eastern grey kangaroo', 'Macropus giganteus');
insert into animal (nombreComun, nombreCientifico) values ('Lappet-faced vulture', 'Aegypius tracheliotus');
insert into animal (nombreComun, nombreCientifico) values ('American black bear', 'Ursus americanus');
insert into animal (nombreComun, nombreCientifico) values ('Australian magpie', 'Gymnorhina tibicen');
insert into animal (nombreComun, nombreCientifico) values ('Baboon, gelada', 'Theropithecus gelada');
insert into animal (nombreComun, nombreCientifico) values ('Andean goose', 'Chloephaga melanoptera');
insert into animal (nombreComun, nombreCientifico) values ('Neotropic cormorant', 'Phalacrocorax brasilianus');
insert into animal (nombreComun, nombreCientifico) values ('Polecat, african', 'Ictonyx striatus');
insert into animal (nombreComun, nombreCientifico) values ('Squirrel, red', 'Tamiasciurus hudsonicus');
insert into animal (nombreComun, nombreCientifico) values ('Wallaby, euro', 'Macropus robustus');
insert into animal (nombreComun, nombreCientifico) values ('Greater blue-eared starling', 'Lamprotornis chalybaeus');
insert into animal (nombreComun, nombreCientifico) values ('Sunbird, lesser double-collared', 'Nectarinia chalybea');
insert into animal (nombreComun, nombreCientifico) values ('Whale, southern right', 'Eubalaena australis');
insert into animal (nombreComun, nombreCientifico) values ('Horned lark', 'Eremophila alpestris');
insert into animal (nombreComun, nombreCientifico) values ('White-winged dove', 'Zenaida asiatica');
insert into animal (nombreComun, nombreCientifico) values ('Mountain goat', 'Oreamnos americanus');
insert into animal (nombreComun, nombreCientifico) values ('Anteater, giant', 'Myrmecophaga tridactyla');
insert into animal (nombreComun, nombreCientifico) values ('Brown and yellow marshbird', 'Pseudoleistes virescens');
insert into animal (nombreComun, nombreCientifico) values ('Owl, white-browed', 'Ninox superciliaris');
insert into animal (nombreComun, nombreCientifico) values ('Grouse, sage', 'Centrocercus urophasianus');
insert into animal (nombreComun, nombreCientifico) values ('Long-billed corella', 'Cacatua tenuirostris');
insert into animal (nombreComun, nombreCientifico) values ('White-winged tern', 'Chlidonias leucopterus');
insert into animal (nombreComun, nombreCientifico) values ('Starling, red-shouldered glossy', 'Lamprotornis nitens');
insert into animal (nombreComun, nombreCientifico) values ('Cougar', 'Felis concolor');
insert into animal (nombreComun, nombreCientifico) values ('Sheep, stone', 'Ovis dalli stonei');
insert into animal (nombreComun, nombreCientifico) values ('Kangaroo, western grey', 'Macropus fuliginosus');
insert into animal (nombreComun, nombreCientifico) values ('Lorikeet, scaly-breasted', 'Trichoglossus chlorolepidotus');
insert into animal (nombreComun, nombreCientifico) values ('Margay', 'Felis wiedi or Leopardus weidi');
insert into animal (nombreComun, nombreCientifico) values ('Squirrel, red', 'Tamiasciurus hudsonicus');
insert into animal (nombreComun, nombreCientifico) values ('Carpet python', 'Morelia spilotes variegata');
insert into animal (nombreComun, nombreCientifico) values ('Emerald green tree boa', 'Boa caninus');
insert into animal (nombreComun, nombreCientifico) values ('Little brown bat', 'Myotis lucifugus');
insert into animal (nombreComun, nombreCientifico) values ('Roe deer', 'Capreolus capreolus');
insert into animal (nombreComun, nombreCientifico) values ('Galapagos dove', 'Zenaida galapagoensis');
insert into animal (nombreComun, nombreCientifico) values ('Glossy ibis', 'Plegadis falcinellus');
insert into animal (nombreComun, nombreCientifico) values ('Mourning collared dove', 'Streptopelia decipiens');
insert into animal (nombreComun, nombreCientifico) values ('Turtle (unidentified)', 'unavailable');
insert into animal (nombreComun, nombreCientifico) values ('Gorilla, western lowland', 'Gorilla gorilla');
insert into animal (nombreComun, nombreCientifico) values ('Vulture, griffon', 'Gyps fulvus');
insert into animal (nombreComun, nombreCientifico) values ('Finch, common melba', 'Pytilia melba');
insert into animal (nombreComun, nombreCientifico) values ('Squirrel, malabar', 'Ratufa indica');
insert into animal (nombreComun, nombreCientifico) values ('Macaque, rhesus', 'Macaca mulatta');
insert into animal (nombreComun, nombreCientifico) values ('Dragon, ornate rock', 'Ctenophorus ornatus');
insert into animal (nombreComun, nombreCientifico) values ('Squirrel, grey-footed', 'Paraxerus cepapi');
insert into animal (nombreComun, nombreCientifico) values ('Comb duck', 'Sarkidornis melanotos');
insert into animal (nombreComun, nombreCientifico) values ('Puma, south american', 'Felis concolor');
insert into animal (nombreComun, nombreCientifico) values ('Capybara', 'Hydrochoerus hydrochaeris');
insert into animal (nombreComun, nombreCientifico) values ('Cook''s tree boa', 'Corallus hortulanus cooki');
insert into animal (nombreComun, nombreCientifico) values ('Sea birds (unidentified)', 'unavailable');
insert into animal (nombreComun, nombreCientifico) values ('Butterfly, canadian tiger swallowtail', 'Papilio canadensis');
insert into animal (nombreComun, nombreCientifico) values ('Leopard, indian', 'Panthera pardus');
insert into animal (nombreComun, nombreCientifico) values ('Prehensile-tailed porcupine', 'Coendou prehensilis');
insert into animal (nombreComun, nombreCientifico) values ('Barrows goldeneye', 'Bucephala clangula');
insert into animal (nombreComun, nombreCientifico) values ('American crow', 'Corvus brachyrhynchos');
