package teoria.salidaCaracteres;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;

public class Ejemplo1 {
    public static void main(String[] args) {
        File outFile = new File("OUTPUT_FILES/fichero2.txt");
        //siempre vamos a usar un PrintWriter para escribir ficheros de texto
        String frase = "En estas pláticas y otras semejantes llegaron al lugar a la hora que anochecía; pero el labrador aguardó a que fuese algo más noche, porque no viesen al molido hidalgo tan mal caballero. Llegada, pues, la hora que le pareció, entró en el pueblo y en casa de Don Quijote, la cual halló toda alborotada, y estaban en ella el cura y el barbero del lugar, que eran grandes amigos de Don Quijote, que estaba diciéndoles su ama a voces: ¿qué le parece a vuestra merced, señor licenciado, Pero Pérez, que así se llamaba el cura, de la desgracia de mi señor? Seis días ha que no parecen él, ni el rocín, ni la adarga, ni la lanza, ni las armas. ¡Desventurada de mí! que me doy a entender, y así es ello la verdad como nací para morir, que estos malditos libros de caballerías que él tiene, y suele leer tan de ordinario, le\n" +
                "han vuelto el juicio; que ahora me acuerdo haberle oído decir muchas veces hablando entre sí, que quería hacerse caballero andante, e irse a buscar las aventuras por esos mundos. Encomendados sean a Satanás y a Barrabás tales libros, que así han echado a perder el más delicado entendimiento que había en toda la Mancha. La sobrina decía lo mismo, y aún decía más: sepa, señor maese Nicolás, que este era el nombre del barbero, que muchas veces le aconteció a mi señor tío estarse leyendo en estos desalmados libros de desventuras dos días con sus noches: al cabo de los cuales arrojaba el libro de las manos, y ponía mano a la espada, y andaba a cuchilladas con las paredes; y cuando estaba muy cansado, decía que había muerto a cuatro gigantes como cuatro torres, y el sudor que sudaba del cansancio decía que era sangre de las feridas que había recibido en la batalla; y bebíase luego un gan jarro de agua fría, y quedaba sano y sosegado, diciendo que aquella agua era una preciosísisma bebida que le había traído el sabio Esquife, un grande encantador y amigo suyo. Mas yo me tengo la culpa de todo, que no avisé a vuestras mercedes de los disparates de mi señor tío, para que lo remediaran antes de llegar a lo que ha llegado, y quemaran todos estos descomulgados libros (que tiene muchos), que bien merecen ser abrasados como si fuesen de herejes. Esto digo yo también, dijo el cura, y a fe que no se pase el día de mañana sin que de ellos no se haga auto público, y sean condenados al fuego, porque no den ocasión a quien los leyere de hacer lo que mi buen amigo debe de haber hecho.\n" +
                "Todo esto estaban oyendo el labrador y Don Quijote, con que acabó de entender el labrador la enfermedad de su vecino, y así comenzó a decir a voces: abran vuestras mercedes al señor Baldovinos y al señor marqués de Mantua, que viene mal ferido, y al señor moro Abindarráez, que trae cautivo el valeroso Rodrigo de Narváez, alcaide de Antequera. A estas voces salieron todos, y como conocieron los unos a su amigo, las otras a su amo y tío, que aún no se había apeado del jumento, porque no podía, corrieron a abrazarle. El dijo: ténganse todos, que vengo mal ferido por la culpa de mi caballo; llévenme a mi lecho, y llámese si fuere posible, a la sabia Urganda, que cure y cate mis feridas. Mirad en hora mala, dijo a este punto el ama, si me decía a mí bien mi corazón del pie que cojeaba mi señor. Suba vuestra merced en buena hora, que sin que venga esa Urganda le sabremos aquí curar. Malditos, digo, sean otra vez y otras ciento estos libros de caballería que tal han parado a vuestra merced.\n" +
                "Lleváronle luego a la cama, y catándole las feridas, no le hallaron ninguna; y él dijo que todo era molimiento, por haber dado una gran caída con Rocinante, su caballo, combatiéndose con diez jayanes, los más desaforados y atrevidos que pudieran fallar en gran parte de la tierra. Ta, Ta, dijo el cura; ¿jayanes hay en la danza? para mí santiguada, que yo los queme mañana antes de que llegue la noche. Hiciéronle a Don Quijote mil preguntas, y a ninguna quiso responder otra cosa, sino que le\n" +
                "diesen de comer y le dejasen dormir, que era lo que más le importaba. Hízose así, y el cura se informó muy a la larga del labrador, del modo que había hallado a Don Quijote. El se lo contó todo con los disparates que al hallarle y al traerle había dicho, que fue poner más deseo en el licenciado de hacer lo que el otro día hizo, que fue llevar a su amigo el barbero maese Nicolás, con el cual se vino a casa de Don Quijote.";
        try (PrintWriter out = new PrintWriter(outFile)) {
            out.write(frase);
            out.flush();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        System.out.printf("Creado fichero %s de %d bytes%n", outFile, outFile.length());

    }
}
